// <auto-generated />
using System;
using Codelingo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Codelingo.Api.Migrations
{
    [DbContext(typeof(CodelingoDbContext))]
    [Migration("20260912050309_ExpandCurriculum")]
    partial class ExpandCurriculum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Codelingo.Api.Models.ExerciseAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exercise_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lesson_id");

                    b.Property<string>("SubmittedAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("submitted_answer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("XpAwarded")
                        .HasColumnType("integer")
                        .HasColumnName("xp_awarded");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("UserId");

                    b.ToTable("exercise_attempts", null, t =>
                        {
                            t.HasCheckConstraint("chk_attempt_language", "language IN ('python','javascript','typescript','csharp','go','rust','java','cpp')");
                        });
                });

            modelBuilder.Entity("Codelingo.Api.Models.LanguageProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompletedLessons")
                        .HasColumnType("integer")
                        .HasColumnName("completed_lessons");

                    b.Property<decimal>("CompletionPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("completion_percentage");

                    b.Property<int>("CurrentLesson")
                        .HasColumnType("integer")
                        .HasColumnName("current_lesson");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<int>("TotalLessons")
                        .HasColumnType("integer")
                        .HasColumnName("total_lessons");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Language")
                        .IsUnique();

                    b.ToTable("language_progress", null, t =>
                        {
                            t.HasCheckConstraint("chk_progress_language", "language IN ('python','javascript','typescript','csharp','go','rust','java','cpp')");
                        });
                });

            modelBuilder.Entity("Codelingo.Api.Models.LessonProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lesson_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("XpAwarded")
                        .HasColumnType("integer")
                        .HasColumnName("xp_awarded");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Language", "LessonId")
                        .IsUnique();

                    b.ToTable("lesson_progress", null, t =>
                        {
                            t.HasCheckConstraint("chk_lesson_language", "language IN ('python','javascript','typescript','csharp','go','rust','java','cpp')");
                        });
                });

            modelBuilder.Entity("Codelingo.Api.Models.SwellProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AnalyticalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("analytical_score");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<decimal>("PracticalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("practical_score");

                    b.Property<string>("PrimaryTrait")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("primary_trait");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("SwellExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("swell_external_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("VisualScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("visual_score");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("swell_profiles", null, t =>
                        {
                            t.HasCheckConstraint("chk_personality", "primary_trait IN ('ANALYTICAL','PRACTICAL','VISUAL')");
                        });
                });

            modelBuilder.Entity("Codelingo.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActiveLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("active_language");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer")
                        .HasColumnName("total_xp");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("chk_active_language", "active_language IN ('python','javascript','typescript','csharp','go','rust','java','cpp')");
                        });
                });

            modelBuilder.Entity("Codelingo.Api.Models.UserStreak", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<DateOnly?>("LastActivityDate")
                        .HasColumnType("date")
                        .HasColumnName("last_activity_date");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("longest_streak");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_streaks", (string)null);
                });

            modelBuilder.Entity("Codelingo.Api.Models.ExerciseAttempt", b =>
                {
                    b.HasOne("Codelingo.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Codelingo.Api.Models.LanguageProgress", b =>
                {
                    b.HasOne("Codelingo.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Codelingo.Api.Models.LessonProgress", b =>
                {
                    b.HasOne("Codelingo.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Codelingo.Api.Models.SwellProfile", b =>
                {
                    b.HasOne("Codelingo.Api.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Codelingo.Api.Models.SwellProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Codelingo.Api.Models.UserStreak", b =>
                {
                    b.HasOne("Codelingo.Api.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Codelingo.Api.Models.UserStreak", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
