import type { UiLanguage } from "../context/OnboardingContext";
import type { FlagCode } from "./icons";

export const UI_LOCALES: Array<{ id: UiLanguage; label: string; flag: FlagCode }> = [
  { id: "es", label: "Español", flag: "es" }, { id: "en", label: "English", flag: "us" },
  { id: "fr", label: "Français", flag: "fr" }, { id: "de", label: "Deutsch", flag: "de" },
  { id: "ja", label: "日本語", flag: "jp" }, { id: "it", label: "Italiano", flag: "it" },
  { id: "pt", label: "Português", flag: "br" }, { id: "zh", label: "中文", flag: "cn" },
  { id: "ko", label: "한국어", flag: "kr" }, { id: "ru", label: "Русский", flag: "ru" },
  { id: "ar", label: "العربية", flag: "sa" },
];

const copy = {
  en: { subjects: "Subjects", coding: "Coding", languages: "Languages", math: "Math", menu: "Menu", learnPath: "Learn Path", progress: "Progress", achievements: "Achievements", profile: "Profile", leaderboard: "Leaderboard", quests: "Daily Quests", activeTrack: "Active Track", mastery: "Mastery", completed: "completed", lessons: "lessons", welcome: "Welcome back", continueTrack: "Let's continue your track.", explanationLanguage: "Explanation language", demoProfile: "Demo Profile", streak: "Streak", days: "days", totalXp: "Total XP", connected: "Louis: connected", companion: "Your learning companion is active", earnedMilestones: "Earned Milestones", tracks: "Programming Languages & Tracks", overall: "Overall", reduce: "Reduce", novice: "Novice", check: "Check", continue: "Continue", tryAgain: "Try Again", correctAnswer: "Correct answer", beforeBegin: "Before you begin", quickExplanation: "A quick explanation", startLesson: "Start Lesson", problem: "Problem", attemptsUsed: "attempts used" },
  es: { subjects: "Materias", coding: "Programación", languages: "Idiomas", math: "Matemáticas", menu: "Menú", learnPath: "Ruta de aprendizaje", progress: "Progreso", achievements: "Logros", profile: "Perfil", leaderboard: "Clasificación", quests: "Retos diarios", activeTrack: "Ruta activa", mastery: "Dominio", completed: "completado", lessons: "lecciones", welcome: "Bienvenido de nuevo", continueTrack: "Continuemos con tu ruta.", explanationLanguage: "Idioma de explicación", demoProfile: "Perfil demo", streak: "Racha", days: "días", totalXp: "XP total", connected: "Louis: conectado", companion: "Tu compañero de aprendizaje está activo", earnedMilestones: "Logros obtenidos", tracks: "Lenguajes y rutas", overall: "General", reduce: "Reducir", novice: "Principiante", check: "Comprobar", continue: "Continuar", tryAgain: "Intentar de nuevo", correctAnswer: "Respuesta correcta", beforeBegin: "Antes de comenzar", quickExplanation: "Una explicación rápida", startLesson: "Comenzar lección", problem: "Problema", attemptsUsed: "intentos usados" },
  fr: { subjects: "Matières", coding: "Programmation", languages: "Langues", math: "Mathématiques", menu: "Menu", learnPath: "Parcours", progress: "Progrès", achievements: "Réussites", profile: "Profil", leaderboard: "Classement", quests: "Défis quotidiens", activeTrack: "Parcours actif", mastery: "Maîtrise", completed: "terminé", lessons: "leçons", welcome: "Bon retour", continueTrack: "Continuons ton parcours.", explanationLanguage: "Langue des explications", demoProfile: "Profil démo", streak: "Série", days: "jours", totalXp: "XP total", connected: "Louis : connecté", companion: "Ton compagnon d'apprentissage est actif", earnedMilestones: "Réussites obtenues", tracks: "Langages et parcours", overall: "Global", reduce: "Réduire", novice: "Débutant", check: "Vérifier", continue: "Continuer", tryAgain: "Réessayer", correctAnswer: "Bonne réponse", beforeBegin: "Avant de commencer", quickExplanation: "Une explication rapide", startLesson: "Commencer la leçon", problem: "Problème", attemptsUsed: "tentatives utilisées" },
} as const;

export type UiTextKey = keyof typeof copy.en;

const extendedCopy: Partial<Record<UiLanguage, Partial<Record<UiTextKey, string>>>> = {
  de: { subjects: "Fächer", coding: "Programmieren", languages: "Sprachen", math: "Mathematik", menu: "Menü", learnPath: "Lernpfad", progress: "Fortschritt", achievements: "Erfolge", profile: "Profil", leaderboard: "Rangliste", quests: "Tägliche Aufgaben", activeTrack: "Aktiver Kurs", mastery: "Meisterschaft", completed: "abgeschlossen", lessons: "Lektionen", welcome: "Willkommen zurück", continueTrack: "Setzen wir deinen Kurs fort.", explanationLanguage: "Sprache der Oberfläche", demoProfile: "Demo-Profil", streak: "Serie", days: "Tage", totalXp: "Gesamt-XP", connected: "Louis: verbunden", companion: "Dein Lernbegleiter ist aktiv", earnedMilestones: "Erreichte Meilensteine", tracks: "Programmiersprachen & Kurse", overall: "Gesamt", reduce: "Verkleinern", novice: "Anfänger", check: "Prüfen", continue: "Weiter", tryAgain: "Erneut versuchen", correctAnswer: "Richtige Antwort", beforeBegin: "Bevor du beginnst", quickExplanation: "Kurze Erklärung", startLesson: "Lektion starten", problem: "Aufgabe", attemptsUsed: "Versuche verwendet" },
  ja: { subjects: "科目", coding: "プログラミング", languages: "言語", math: "数学", menu: "メニュー", learnPath: "学習パス", progress: "進捗", achievements: "実績", profile: "プロフィール", leaderboard: "ランキング", quests: "デイリークエスト", activeTrack: "現在のコース", mastery: "習熟度", completed: "完了", lessons: "レッスン", welcome: "おかえりなさい", continueTrack: "コースを続けましょう。", explanationLanguage: "画面の言語", demoProfile: "デモプロフィール", streak: "連続記録", days: "日", totalXp: "合計XP", connected: "Louis：接続中", companion: "学習パートナーが活動中です", earnedMilestones: "獲得したマイルストーン", tracks: "プログラミング言語とコース", overall: "全体", reduce: "縮小", novice: "初心者", check: "確認", continue: "続ける", tryAgain: "もう一度", correctAnswer: "正解", beforeBegin: "始める前に", quickExplanation: "簡単な説明", startLesson: "レッスン開始", problem: "問題", attemptsUsed: "使用した回数" },
  it: { subjects: "Materie", coding: "Programmazione", languages: "Lingue", math: "Matematica", menu: "Menu", learnPath: "Percorso", progress: "Progressi", achievements: "Traguardi", profile: "Profilo", leaderboard: "Classifica", quests: "Sfide giornaliere", activeTrack: "Percorso attivo", mastery: "Padronanza", completed: "completato", lessons: "lezioni", welcome: "Bentornato", continueTrack: "Continuiamo il tuo percorso.", explanationLanguage: "Lingua dell'interfaccia", demoProfile: "Profilo demo", streak: "Serie", days: "giorni", totalXp: "XP totali", connected: "Louis: connesso", companion: "Il tuo compagno di studio è attivo", earnedMilestones: "Traguardi ottenuti", tracks: "Linguaggi e percorsi", overall: "Totale", reduce: "Riduci", novice: "Principiante", check: "Controlla", continue: "Continua", tryAgain: "Riprova", correctAnswer: "Risposta corretta", beforeBegin: "Prima di iniziare", quickExplanation: "Una breve spiegazione", startLesson: "Inizia lezione", problem: "Problema", attemptsUsed: "tentativi usati" },
  pt: { subjects: "Matérias", coding: "Programação", languages: "Idiomas", math: "Matemática", menu: "Menu", learnPath: "Trilha de aprendizagem", progress: "Progresso", achievements: "Conquistas", profile: "Perfil", leaderboard: "Classificação", quests: "Desafios diários", activeTrack: "Trilha ativa", mastery: "Domínio", completed: "concluído", lessons: "lições", welcome: "Bem-vindo de volta", continueTrack: "Vamos continuar sua trilha.", explanationLanguage: "Idioma da interface", demoProfile: "Perfil demo", streak: "Sequência", days: "dias", totalXp: "XP total", connected: "Louis: conectado", companion: "Seu companheiro de aprendizagem está ativo", earnedMilestones: "Marcos conquistados", tracks: "Linguagens e trilhas", overall: "Geral", reduce: "Reduzir", novice: "Iniciante", check: "Verificar", continue: "Continuar", tryAgain: "Tentar novamente", correctAnswer: "Resposta correta", beforeBegin: "Antes de começar", quickExplanation: "Uma explicação rápida", startLesson: "Iniciar lição", problem: "Problema", attemptsUsed: "tentativas usadas" },
  zh: { subjects: "科目", coding: "编程", languages: "语言", math: "数学", menu: "菜单", learnPath: "学习路径", progress: "进度", achievements: "成就", profile: "个人资料", leaderboard: "排行榜", quests: "每日任务", activeTrack: "当前课程", mastery: "掌握度", completed: "已完成", lessons: "课程", welcome: "欢迎回来", continueTrack: "继续你的学习路径。", explanationLanguage: "界面语言", demoProfile: "演示资料", streak: "连续学习", days: "天", totalXp: "总 XP", connected: "Louis：已连接", companion: "你的学习伙伴在线", earnedMilestones: "已获里程碑", tracks: "编程语言与课程", overall: "总计", reduce: "收起", novice: "初学者", check: "检查", continue: "继续", tryAgain: "再试一次", correctAnswer: "正确答案", beforeBegin: "开始之前", quickExplanation: "简短说明", startLesson: "开始课程", problem: "问题", attemptsUsed: "已用次数" },
  ko: { subjects: "과목", coding: "프로그래밍", languages: "언어", math: "수학", menu: "메뉴", learnPath: "학습 경로", progress: "진행 상황", achievements: "업적", profile: "프로필", leaderboard: "순위표", quests: "일일 퀘스트", activeTrack: "현재 코스", mastery: "숙련도", completed: "완료", lessons: "레슨", welcome: "돌아오신 것을 환영합니다", continueTrack: "학습을 계속해요.", explanationLanguage: "인터페이스 언어", demoProfile: "데모 프로필", streak: "연속 학습", days: "일", totalXp: "총 XP", connected: "Louis: 연결됨", companion: "학습 친구가 활동 중입니다", earnedMilestones: "달성한 이정표", tracks: "프로그래밍 언어와 코스", overall: "전체", reduce: "접기", novice: "초급", check: "확인", continue: "계속", tryAgain: "다시 시도", correctAnswer: "정답", beforeBegin: "시작하기 전에", quickExplanation: "간단한 설명", startLesson: "레슨 시작", problem: "문제", attemptsUsed: "사용한 시도" },
  ru: { subjects: "Предметы", coding: "Программирование", languages: "Языки", math: "Математика", menu: "Меню", learnPath: "Путь обучения", progress: "Прогресс", achievements: "Достижения", profile: "Профиль", leaderboard: "Рейтинг", quests: "Ежедневные задания", activeTrack: "Активный курс", mastery: "Освоение", completed: "завершено", lessons: "уроков", welcome: "С возвращением", continueTrack: "Продолжим ваш курс.", explanationLanguage: "Язык интерфейса", demoProfile: "Демо-профиль", streak: "Серия", days: "дней", totalXp: "Всего XP", connected: "Louis: подключён", companion: "Ваш помощник активен", earnedMilestones: "Полученные достижения", tracks: "Языки программирования и курсы", overall: "Всего", reduce: "Свернуть", novice: "Новичок", check: "Проверить", continue: "Продолжить", tryAgain: "Попробовать снова", correctAnswer: "Правильный ответ", beforeBegin: "Перед началом", quickExplanation: "Краткое объяснение", startLesson: "Начать урок", problem: "Задача", attemptsUsed: "попыток использовано" },
  ar: { subjects: "المواد", coding: "البرمجة", languages: "اللغات", math: "الرياضيات", menu: "القائمة", learnPath: "مسار التعلم", progress: "التقدم", achievements: "الإنجازات", profile: "الملف الشخصي", leaderboard: "لوحة الصدارة", quests: "المهام اليومية", activeTrack: "المسار النشط", mastery: "الإتقان", completed: "مكتمل", lessons: "دروس", welcome: "مرحبًا بعودتك", continueTrack: "لنواصل مسارك.", explanationLanguage: "لغة الواجهة", demoProfile: "ملف تجريبي", streak: "السلسلة", days: "أيام", totalXp: "إجمالي XP", connected: "Louis: متصل", companion: "رفيق التعلم نشط", earnedMilestones: "الإنجازات المكتسبة", tracks: "لغات البرمجة والمسارات", overall: "الإجمالي", reduce: "تصغير", novice: "مبتدئ", check: "تحقق", continue: "متابعة", tryAgain: "حاول مجددًا", correctAnswer: "الإجابة الصحيحة", beforeBegin: "قبل أن تبدأ", quickExplanation: "شرح سريع", startLesson: "ابدأ الدرس", problem: "مسألة", attemptsUsed: "محاولات مستخدمة" },
};

export function uiText(locale: UiLanguage | null, key: UiTextKey) {
  if (locale === "es" || locale === "fr") return copy[locale][key];
  return extendedCopy[locale ?? "en"]?.[key] ?? copy.en[key];
}
