import type { UiLanguage } from "../context/OnboardingContext";

const coding = {
  hello: { es: ["Hola Mundo", "Aprende la sintaxis básica y muestra texto.", "Un programa usa una función de salida para mostrar texto. Respeta exactamente las comillas, mayúsculas y puntuación solicitadas.", "Escribe el programa que muestra el saludo solicitado."], fr: ["Bonjour le monde", "Apprends la syntaxe de base et affiche du texte.", "Un programme utilise une fonction de sortie pour afficher du texte. Respecte exactement les guillemets, les majuscules et la ponctuation demandés.", "Écris le programme qui affiche le message demandé."] },
  variables: { es: ["Variables y tipos", "Guarda datos con nombres y tipos claros.", "Una variable asocia un nombre a un valor. El tipo determina qué valores y operaciones son válidos.", "Declara la variable solicitada con el valor correcto."], fr: ["Variables et types", "Stocke des données avec des noms et des types clairs.", "Une variable associe un nom à une valeur. Son type détermine les valeurs et les opérations autorisées.", "Déclare la variable demandée avec la bonne valeur."] },
  conditions: { es: ["Condiciones", "Controla decisiones con expresiones booleanas.", "Una condición ejecuta un bloque únicamente cuando su expresión es verdadera. Compara los valores con el operador adecuado.", "Escribe la condición que cumple la regla indicada."], fr: ["Conditions", "Contrôle les décisions avec des expressions booléennes.", "Une condition exécute un bloc uniquement lorsque son expression est vraie. Compare les valeurs avec le bon opérateur.", "Écris la condition qui respecte la règle indiquée."] },
  functions: { es: ["Funciones", "Organiza lógica reutilizable con parámetros.", "Una función recibe parámetros, realiza una tarea y puede devolver un resultado. Mantén claros sus tipos y su valor de retorno.", "Escribe la función solicitada."], fr: ["Fonctions", "Organise une logique réutilisable avec des paramètres.", "Une fonction reçoit des paramètres, effectue une tâche et peut renvoyer un résultat. Garde des types et une valeur de retour clairs.", "Écris la fonction demandée."] },
  loops: { es: ["Bucles", "Repite instrucciones de forma controlada.", "Un bucle repite un bloque mientras se cumpla una regla. Define con cuidado el inicio, el límite y el avance.", "Escribe el bucle solicitado."], fr: ["Boucles", "Répète des instructions de façon contrôlée.", "Une boucle répète un bloc selon une règle. Définis soigneusement le départ, la limite et l'incrément.", "Écris la boucle demandée."] },
  arrays: { es: ["Arreglos y colecciones", "Trabaja con varios valores ordenados.", "Una colección guarda varios elementos. Los índices permiten leer o modificar una posición concreta.", "Crea o modifica la colección solicitada."], fr: ["Tableaux et collections", "Travaille avec plusieurs valeurs ordonnées.", "Une collection stocke plusieurs éléments. Les index permettent de lire ou modifier une position précise.", "Crée ou modifie la collection demandée."] },
  oop: { es: ["Clases y estructuras", "Agrupa datos y comportamiento relacionado.", "Una clase o estructura modela una entidad con propiedades y métodos relacionados.", "Define el tipo solicitado con sus propiedades."], fr: ["Classes et structures", "Regroupe les données et les comportements liés.", "Une classe ou une structure modélise une entité avec des propriétés et des méthodes liées.", "Définis le type demandé avec ses propriétés."] },
  async: { es: ["Programación asíncrona", "Coordina tareas que terminan más tarde.", "El código asíncrono espera operaciones sin bloquear innecesariamente el programa.", "Completa la operación asíncrona solicitada."], fr: ["Programmation asynchrone", "Coordonne les tâches qui se terminent plus tard.", "Le code asynchrone attend des opérations sans bloquer inutilement le programme.", "Complète l'opération asynchrone demandée."] },
  errors: { es: ["Manejo de errores", "Detecta y recupera fallos esperados.", "El manejo de errores separa el camino normal de las situaciones excepcionales y permite recuperarse con seguridad.", "Agrega el manejo de errores solicitado."], fr: ["Gestion des erreurs", "Détecte et récupère les erreurs prévues.", "La gestion des erreurs sépare le chemin normal des situations exceptionnelles et permet une récupération sûre.", "Ajoute la gestion des erreurs demandée."] },
  generics: { es: ["Genéricos", "Reutiliza lógica conservando la seguridad de tipos.", "Los genéricos permiten escribir una operación para varios tipos sin perder información de tipo.", "Escribe la versión genérica solicitada."], fr: ["Génériques", "Réutilise la logique tout en conservant la sûreté des types.", "Les génériques permettent d'écrire une opération pour plusieurs types sans perdre les informations de type.", "Écris la version générique demandée."] },
} as const;

export function lessonCopy(id: string, locale: UiLanguage | null, fallback: { title: string; description?: string; explanation?: string | null; prompt?: string }) {
  const language = locale === "es" || locale === "fr" ? locale : null;
  const translated = coding[id as keyof typeof coding]?.[language as "es" | "fr"];
  return translated ? { title: translated[0], description: translated[1], explanation: translated[2], prompt: translated[3] } : { title: fallback.title, description: fallback.description ?? "", explanation: fallback.explanation ?? "", prompt: fallback.prompt ?? "" };
}
