import { useMemo, useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { Check, Code2, Sprout, BarChart3, Braces, Trophy } from "lucide-react";
import { useOnboarding, type ExperienceLevel, type ProgrammingTrack, type UiLanguage } from "../context/OnboardingContext";
import { LouisPrompt, OnboardingShell, primaryButton } from "../components/onboarding/OnboardingShell";
import { placementQuestions, recommendation } from "../lib/placement";
import { SUPPORTED_LANGUAGES } from "../lib/constants";
import { DEMO_USER_ID } from "../lib/constants";
import { completeOnboarding, saveOnboardingPreferences, savePlacement } from "../api/onboarding";

const optionClass = (selected: boolean) => `relative rounded-2xl border-2 p-5 text-left font-bold transition ${selected ? "border-red-600 bg-red-50 dark:bg-red-950/30" : "border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 hover:border-slate-400"}`;

export function LanguageStep() {
  const { state, update } = useOnboarding(); const navigate = useNavigate();
  const options: {id: UiLanguage; label: string; detail: string}[] = [{id:"es",label:"Español",detail:"Explicaciones y ayuda en español"},{id:"en",label:"English",detail:"Lessons and help in English"}];
  return <OnboardingShell step={1} backTo="/"><LouisPrompt>¿En qué idioma quieres recibir las explicaciones?</LouisPrompt><h1 className="text-3xl sm:text-4xl font-black text-center mb-8">Choose your explanation language</h1><div className="grid sm:grid-cols-2 gap-4">{options.map(o=><button key={o.id} onClick={()=>update({uiLanguage:o.id})} className={optionClass(state.uiLanguage===o.id)}><span className="text-xl">{o.label}</span><span className="block mt-1 text-sm text-slate-500">{o.detail}</span>{state.uiLanguage===o.id&&<Check className="absolute right-4 top-4 text-red-600"/>}</button>)}</div><button disabled={!state.uiLanguage} onClick={()=>navigate('/onboarding/track')} className={`${primaryButton} mt-8`}>CONTINUE</button></OnboardingShell>;
}

export function TrackStep() {
  const { state, update } = useOnboarding(); const navigate=useNavigate(); const tracks: ProgrammingTrack[]=["python","javascript","typescript","csharp"];
  if(!state.uiLanguage)return <Navigate to="/onboarding/language" replace/>;
  return <OnboardingShell step={2} backTo="/onboarding/language"><LouisPrompt>What do you want to program first?</LouisPrompt><h1 className="text-3xl sm:text-4xl font-black text-center mb-8">Choose your programming track</h1><div className="grid sm:grid-cols-2 gap-4">{tracks.map(id=><button key={id} onClick={()=>update({programmingLanguage:id,placementAnswers:{},placementScore:null,recommendedLessonId:null})} className={optionClass(state.programmingLanguage===id)}><Code2 className="mb-3 text-red-600"/><span className="text-xl">{SUPPORTED_LANGUAGES[id].label}</span><span className="block mt-1 text-sm text-slate-500">{SUPPORTED_LANGUAGES[id].description}</span>{state.programmingLanguage===id&&<Check className="absolute right-4 top-4 text-red-600"/>}</button>)}</div><p className="text-center text-sm text-slate-500 mt-5">Go, Rust, Java and C++ remain available from the dashboard.</p><button disabled={!state.programmingLanguage} onClick={()=>navigate('/onboarding/experience')} className={`${primaryButton} mt-6`}>CONTINUE</button></OnboardingShell>;
}

export function ExperienceStep() {
  const { state,update }=useOnboarding();const navigate=useNavigate(); if(!state.programmingLanguage)return <Navigate to="/onboarding/track" replace/>;
  const levels:{id:ExperienceLevel;label:string;detail:string;icon:typeof Sprout}[]=[{id:"beginner",label:"I'm starting from zero",detail:"I have never programmed before.",icon:Sprout},{id:"basic",label:"I know variables and conditions",detail:"I have seen the fundamentals.",icon:BarChart3},{id:"intermediate",label:"I write functions and loops",detail:"I have some programming practice.",icon:Braces},{id:"project_experience",label:"I have built my own projects",detail:"I feel comfortable programming.",icon:Trophy}];
  return <OnboardingShell step={3} backTo="/onboarding/track"><LouisPrompt>How much programming do you already know?</LouisPrompt><div className="space-y-3">{levels.map(l=><button key={l.id} onClick={()=>update({experienceLevel:l.id})} className={`${optionClass(state.experienceLevel===l.id)} w-full flex gap-4 items-center`}><l.icon className="text-red-600"/><span><span className="text-lg">{l.label}</span><span className="block text-sm text-slate-500">{l.detail}</span></span>{state.experienceLevel===l.id&&<Check className="ml-auto text-red-600"/>}</button>)}</div><button disabled={!state.experienceLevel} onClick={()=>navigate('/onboarding/placement')} className={`${primaryButton} mt-8`}>START THE 5-QUESTION TEST</button></OnboardingShell>;
}

export function PlacementStep() {
  const {state,update}=useOnboarding();const navigate=useNavigate();const [index,setIndex]=useState(0);const [selected,setSelected]=useState("");const [checked,setChecked]=useState(false);const qs=useMemo(()=>state.programmingLanguage?placementQuestions(state.programmingLanguage):[],[state.programmingLanguage]);
  if(!state.experienceLevel||!state.programmingLanguage)return <Navigate to="/onboarding/experience" replace/>; const q=qs[index];
  const next=()=>{const answers={...state.placementAnswers,[q.id]:selected};update({placementAnswers:answers});if(index<qs.length-1){setIndex(index+1);setSelected(answers[qs[index+1].id]??"");setChecked(false);}else{const score=qs.filter(x=>(x.id===q.id?selected:answers[x.id])===x.answer).length;update({placementAnswers:answers,placementScore:score,recommendedLessonId:recommendation(score)});navigate('/onboarding/result');}};
  return <OnboardingShell step={4} backTo="/onboarding/experience"><div className="flex items-center justify-between mb-4 font-bold text-slate-500"><span>Question {index+1} of 5</span><span>{SUPPORTED_LANGUAGES[state.programmingLanguage].label}</span></div><LouisPrompt>{q.prompt}</LouisPrompt><pre className="rounded-2xl bg-slate-950 text-slate-100 p-6 text-lg overflow-auto mb-6"><code>{q.code}</code></pre><div className="grid sm:grid-cols-2 gap-3">{q.options.map(o=><button key={o} disabled={checked} onClick={()=>setSelected(o)} className={optionClass(selected===o)}>{o}</button>)}</div>{checked&&<p role="status" className={`mt-5 rounded-xl p-4 font-bold ${selected===q.answer?"bg-emerald-50 text-emerald-800":"bg-amber-50 text-amber-900"}`}>{selected===q.answer?"Correct! Louis is impressed.":`Not quite. The answer is: ${q.answer}`}</p>}<button disabled={!selected} onClick={()=>checked?next():setChecked(true)} className={`${primaryButton} mt-7`}>{checked?(index===4?"SEE MY RESULT":"NEXT"):"CHECK"}</button></OnboardingShell>;
}

export function PlacementResult() {
  const {state,update,reset}=useOnboarding();const navigate=useNavigate();const [saving,setSaving]=useState(false);const [error,setError]=useState(""); if(state.placementScore===null||!state.programmingLanguage||!state.recommendedLessonId||!state.uiLanguage||!state.experienceLevel)return <Navigate to="/onboarding/placement" replace/>; const title=state.recommendedLessonId[0].toUpperCase()+state.recommendedLessonId.slice(1);
  const go=async(lesson:string)=>{setSaving(true);setError("");try{await saveOnboardingPreferences(DEMO_USER_ID,state.uiLanguage!,state.programmingLanguage!,state.experienceLevel!);await savePlacement(DEMO_USER_ID,state.programmingLanguage!,state.placementAnswers);await completeOnboarding(DEMO_USER_ID,lesson);update({completed:true,recommendedLessonId:lesson});localStorage.setItem("codelingo_active_language",state.programmingLanguage!);localStorage.setItem("codelingo_demo_session","true");window.location.assign(`/lesson/${state.programmingLanguage}/${lesson}`);}catch{setError("We could not save the demo recommendation. Check that the backend is running and try again.");setSaving(false);}};
  return <OnboardingShell step={5} backTo="/onboarding/placement"><div className="grid md:grid-cols-[260px_1fr] gap-8 items-center"><img src="/louis-transparent.png" className="w-64 h-64 object-contain mx-auto motion-safe:animate-bounce" alt="Louis celebrating"/><section className="rounded-3xl border-2 border-slate-200 dark:border-slate-700 p-7 bg-white dark:bg-slate-900"><h1 className="text-3xl sm:text-4xl font-black">We found your starting point!</h1><p className="mt-5 text-slate-500 font-bold">Recommendation</p><p className="text-3xl font-black text-red-600">{title} · {SUPPORTED_LANGUAGES[state.programmingLanguage].label}</p><p className="mt-4 text-lg font-bold">{state.placementScore} of 5 correct</p><p className="mt-2 text-slate-600 dark:text-slate-300">Your test recommends a starting point. It does not award XP or mark earlier lessons complete.</p>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-800 font-bold">{error}</p>}<button disabled={saving} onClick={()=>void go(state.recommendedLessonId!)} className={`${primaryButton} mt-7`}>{saving?"SAVING…":`START AT ${title.toUpperCase()}`}</button><button disabled={saving} onClick={()=>void go('hello')} className="w-full mt-3 rounded-2xl border-2 border-slate-200 dark:border-slate-700 px-5 py-4 font-black">REVIEW FROM THE BEGINNING</button><button onClick={()=>{reset();navigate('/onboarding/language')}} className="w-full mt-3 text-sm font-bold text-slate-500 underline">Restart onboarding</button></section></div></OnboardingShell>;
}
